services:
  adminer:
    image: adminer
    restart: always
    depends_on:
      - pgsql
    ports:
      - 8080:8080
    networks:
      - inventory_management_app_network

  pgsql:
    image: 'postgres:17-alpine3.22'
    restart: always
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - '${DB_PORT}:5432' # Fixed: maps external port to internal 5432
    volumes:
      - inventory_management_app_data:/var/lib/postgresql/data
    networks:
      - inventory_management_app_network

  redis:
    image: 'redis:6.2.19-alpine'
    ports:
      - '6379:6379'
    networks:
      - inventory_management_app_network

volumes:
  inventory_management_app_data: # Renamed for clarity

networks:
  inventory_management_app_network:
    driver: bridge
